### ISSUE TITLE
Release backwards incompatible version with more entropy sources

### ISSUE THREAD

**Issue by Valve** [Valve/fingerprintjs#23]
I have an idea to create a new version of fingerprintjs with incompatible changes.
This new version would use flash for fonts sniffing and would use more sophisticated canvas fingerprinting (like more letters, effects, geometrical shapes intersections etc).
This new version will also probe for IE plugins that are particularly popular in China (qq, baidu etc).
Please leave your comments in case you're interested.

Why the need for a separate version? It will return new fingerprints and will not be backwards compatible.
It will also have swfobject and, possibly, jquery as dependencies.

**Comment by firetix** [comment]
+1

**Comment by theseyi** [comment]
+1

**Comment by argent-smith** [comment]
+1

**Comment by garrettwilkin** [comment]
+1

**Comment by Valve** [comment]
I'll release a fingerprintjs2 if 10 users will vote for this, currently it's only 6.

**Comment by atlantis3001** [comment]
+1

**Comment by piront** [comment]
+1

**Comment by msedv** [comment]
+1

**Comment by jordii** [comment]
+1

**Comment by max107** [comment]
+1

**Comment by maceip** [comment]
+1

**Comment by maceip** [comment]
font sniffing is a must, also anything else in here you can implement: http://www.chromium.org/Home/chromium-security/client-identification-mechanisms, https://seclab.cs.ucsb.edu/media/uploads/papers/sp2013_cookieless.pdf
?

**Comment by Valve** [comment]
@maceip thanks for the links, yes, I'll make it detect maximum features, all that I can implement.

**Comment by maceip** [comment]
one more link that maybe relevant (most importantly HTTP header order):
http://engineering.shapesecurity.com/2015/01/detecting-phantomjs-based-visitors.html

**Comment by Valve** [comment]
New repo is here: https://github.com/Valve/fingerprintjs2
Please submit all ideas, thoughts as issues. Any help and criticism is greatly appreciated.

Thank you all, closing issue.

**Comment by Techmind** [comment]
+1
