### ISSUE TITLE
Cross-browser Fingerprinting?

### ISSUE THREAD

**Issue by ipullrank** [Valve/fingerprintjs#27]
Hey Valve,
Great library!

I don't have an issue, but I was wondering if you've considered cross-browser fingerprinting as seen here on http://fingerprint.pet-portal.eu/?

I imagine it'll get around Chrome's automatic updating at least.

**Comment by Valve** [comment]
Hey @ipullrank,
thanks for using the library. 

As I understand it, cross-browser fingerprinting implies removing all browser-specific items and adding instead OS specific items, such as installed fonts. I don't understand why they still list installed browser plugins and the user agent usage on their website. Please clarify it.

**Comment by BobSmithJoe** [comment]
This does not work properly at the link provided (try it in two different browsers), but I would love the ability to track users across browsers. Any plan on adding that?

**Comment by Valve** [comment]
No, no plans for this, sorry. This will remain a strictly browser fingerprinting library. For cross-browser (i.e. user) identification please try commercial products, such as augur.io
