### ISSUE TITLE
ZT devices

### ISSUE THREAD

**Issue by nadien** [Valve/fingerprintjs#28]
What about ZT devices fingerprint? ,

**Comment by Valve** [comment]
Could you please elaborate on your question?

**Comment by nadien** [comment]
I going to buy a device (ZTK LX50), do you thing this device works with fingerprintjs?, i don't know to much about this.

**Comment by simonpucher** [comment]
The Fingerprint library works on every device if there is javascript enabled for the browser. Of course it can suppressed by disabling javascript or using a browser extensions like noscript. EFF did a pretty good overview on this you can find it here: https://panopticlick.eff.org/self-defense.php

**Comment by nadien** [comment]
Well, i think the best way is try this myself, i will use this package and see what happen.
Thanks by the way.
