### ISSUE TITLE
Support for Murmur3 128bit

### ISSUE THREAD

**Issue by yelled3** [Valve/fingerprintjs#30]
@Valve would you consider adding 128bit support?

I saw this was already done in `fingerprintjs2`:
https://github.com/Valve/fingerprintjs2/blob/master/fingerprint2.js#L70-L71

on big data sets hash collisions is a real issue :-)

**Comment by Valve** [comment]
Hi @yelled3 

You can substitute the hashing function easily and use 128bit one.
Unfortunately I don't have much spare time, so I can only fix bugs in FP1. Whenever I have some free time, I try to develop the FP2 library.

Thanks
