### ISSUE TITLE
Error in this parameter

### ISSUE THREAD

**Issue by ronsonmaria** [Valve/fingerprintjs#35]
Hello,

I found one error in the line 86

 keys = this.screenResolutionKey(keys)

I think that you work with resolutions, it's ok, but when the user has two monitors or more, this parameter is different when the windows is in the different screen, so I think that you'd change or omite this parameter.

Thanks for all.

**Comment by Valve** [comment]
Hi, 
There is a configuration option for this. By default it's disabled. Please see lines 64 and 79
