### ISSUE TITLE
View the image?

### ISSUE THREAD

**Issue by prismspecs** [Valve/fingerprintjs#36]
Is it possible to view the actual image that is generated on the canvas?

**Comment by Valve** [comment]
Yes, you can save the `canvas.toDataURL` in a variable here: https://github.com/Valve/fingerprintjs/blob/master/fingerprint.js#L278

and paste the variable value into the browser address bar. The browser will render the URL as the image.

**Comment by AungHlaingWin** [comment]
Hi Valve, I don't understand how to past which variable to canvas.toDataURL. I meant I don't understand how to save fingerprint on my computer. Please, can you show me a full sample code.
Thank you very much!

**Comment by Valve** [comment]
Hi @AungHlaingWin , I don't save fingerprint on your computer. It's not possible for me to save anything on your computer.  You should modify the source code of the library to save the canvas in a var.

```
var image = canvas.toDataURL();
```

Then you can view the image variable in the developer tools debugger and click on its value. The browser will load the image in a new tab. Tested on Google Chrome

**Comment by AungHlaingWin** [comment]
Hi Valve, 
I know that you cant save finger canvas image to my computer.
I meant that I want to save finger canvas image to the same path using fingerprintjs2.js.
But I don't know how to modify the functions to save finger canvas image as png type.
Can you support me with full source code?
And do you mean as following : 

var image = canvas.toDataURL("image/png");

Is it right??
And whare can I save that canvas png image ?
Thank you!

**Comment by Valve** [comment]
I recorded a short video showing how to do it.
https://www.dropbox.com/s/vs4poviqiybsbxr/how%20to%20view%20image.mov?dl=0

**Comment by AungHlaingWin** [comment]
I added img element with id = 'mirror' as follow.
----
" <img src="" id="mirror" class="canvas__mirror" /> "
----
And I modified as you say.Then attach canvas image with img element.
----
var image = canvas.toDataURL("image/png");
mirror.src = image;
----
![ffffff](https://cloud.githubusercontent.com/assets/16250830/11738777/2166565e-a014-11e5-8006-6eb7f2aa361a.png)

Then I can see canvas image. But that is not a fingerprint image.
I captured that image.
