### ISSUE TITLE
the fingerprints.js file will be blocked by uBlock Origin v1.4.0

### ISSUE THREAD

**Issue by lanbin** [Valve/fingerprintjs#37]
but it's ok by useing adblock plus...

**Comment by Valve** [comment]
Seems like you're serving the file separately. uBlock has a rule for this:

/fingerprint.js
/fingerprint.min.js

Just try to rename the file and it should work fine. If it won't, rename the constructor function (thus obfuscating it) and it should work.

**Comment by lanbin** [comment]
Thanks for your suggestion.
