### ISSUE TITLE
Requirejs and Fingerprint

### ISSUE THREAD

**Issue by lexoyo** [Valve/fingerprintjs#38]
Hello
We have an issue with a third party who use our script wich includes this fine library Fingerprint
And this third party uses require.js and he got this error
```
Error: Mismatched anonymous define() module
```
My question is: is Fingerprint supposed to be compatible with require?
Thank you in advance

**Comment by Valve** [comment]
@lexoyo thanks for letting me know. 
I've never used 'require' so cannot comment on this. Please feel free to contribute :)

**Comment by lexoyo** [comment]
Ok thx for your reply
I will contribute if I it turns out it comes from Fingerprint
