### ISSUE TITLE
Got the different result in different time

### ISSUE THREAD

**Issue by roycyz** [Valve/fingerprintjs#41]
The same PC start the test with Xilium.CefGlue.But some time get the different result.Using firefox also have this question.How can I always get the same result in same PC?

**Comment by Valve** [comment]
Please let me know what is Xilium. The library is for browser fingerprinting, not for PC identification. It should work consistently in the same browser, not across different browsers.
Closing now.
If you have the library returning different results in the same browser, please submit a full issue with browser version, operating system and the component that is different for you.
