### ISSUE TITLE
Does not work in Firefox with cookies disabled

### ISSUE THREAD

**Issue by julia-r** [Valve/fingerprintjs#44]
I don't get a fingerprint in Firefox (v51.0) when I have cookies disabled. I get the following error message:

`SecurityError: The operation is insecure.  fingerprint.min.js:1
t.prototype.get http://valve.github.io/fingerprintjs/javascripts/fingerprint.min.js:1:696`

**Comment by Valve** [comment]
thanks for letting me know. Which line throws the error? Are you using the latest version of the library?

**Comment by julia-r** [comment]
Yes, I am using the current version (0.5.4). It also happens on your [demo page](http://valve.github.io/fingerprintjs/) 

![screen shot 2017-01-26 at 09 57 42](https://cloud.githubusercontent.com/assets/5902553/22325467/779c6f52-e3ae-11e6-8fa4-a534bbc265c9.png)

**Comment by Valve** [comment]
you're using the minified version, it's a one-line file. You need to use full, unminified version to get the line which throws the error

**Comment by chrisparnin** [comment]
This may be related to antivirus:

![image](https://cloud.githubusercontent.com/assets/742934/22746097/c1b51fd4-edf0-11e6-863c-b155daf7a60f.png)

**Comment by julia-r** [comment]
Sorry for answering so late. I took a look at it again today and I figured it out: I was using an older version of fingerprint.js. The error was fixed with this commit https://github.com/Valve/fingerprintjs/commit/04c1f8bad3562d7b3675c8c12a87f9b76b18d0df#diff-d4b3d5a1199f9d57ac7b407efb819c93 
It was a bit confusing, because it has the same version number... Anyway, the latest version seems to be working fine now :)
